### PR TITLE
Amqp rpc server accepts custom error handler.

### LINKED ISSUE #25: Revert "let-it-crash" behaviour in favour of an application defined exception handler.
When creating an RPC server, allow the user to specify a custom error handler function that accepts a `Throwable`.

When an RPC call throws, pass the exception to the error handler. If the error handler throws, let the thrown exception bubble. Otherwise, return an internal server error to the client and keep the RPC server running.

@darianbr

### PR DESCRIPTION
**Pull request by darianbr**
Error handler can deal with certain exception (and re-throw others) and then have the rpc continue operation normally afterwards.

Fixes #25.

### CODE REVIEW

**Comment by darianbr** [comment]
@jmalloc fyi

File: src/Amqp/Rpc/AmqpRpcServer.php [hunk 1]
```diff
@@ -275,8 +278,18 @@ private function recv(AMQPMessage $message)
                 'Internal server error.'
             );
 
-            $this->isStopping = true;
-            $this->uncaughtException = $e;
+            if (null !== $this->errorHandler) {
+                try {
+                    $fn = $this->errorHandler;
+                    $fn($e);
+                } catch (Exception $e) {
```
Comment (jmalloc) [inline src/Amqp/Rpc/AmqpRpcServer.php]: I expect this should be `Throwable`, please add a test for this.

File: test/suite/Amqp/Rpc/AmqpRpcServerTest.php [hunk 2]
```diff
@@ -469,6 +471,169 @@ function () {
         }
     }
 
+    public function testReceiveRequestWithCustomErrorHandler()
```
Comment (jmalloc) [inline test/suite/Amqp/Rpc/AmqpRpcServerTest.php]: Assuming this test is largely a duplicate of an existing one, it could be pared down to just test for the specific differences when an exception handler is set.

File: test/suite/Amqp/Rpc/AmqpRpcServerTest.php [hunk 3]
```diff
@@ -469,6 +471,169 @@ function () {
...
+            ->thenReturn(null);
+
+        $someException = new Exception('Error handler throws.');
+        $exceptioned = false;
+
+        $this->server = Phake::partialMock(
+            AmqpRpcServer::class,
+            $this->logger,
+            $this->channel,
+            function (Throwable $e) { throw new Exception('Error handler throws.'); },
```
Comment (jmalloc) [inline test/suite/Amqp/Rpc/AmqpRpcServerTest.php]: I think this is the only line that needs to change in regards to testing for `Throwable` rather than `Exception`, just throw an `Error` to ensure it works with any `Throwable`.

**Comment by jmalloc** [comment]
Oh also, you listed PHP 7.2 in the allow failures list of the CI config, but it's not in the build matrix?

**Comment by jmalloc** [comment]
Can you please also change `ARCHER_PUBLISH_VERSION=5.6` to 7.1 in the Travis config.

File: src/Amqp/JobQueue/AmqpWorker.php [hunk 4]
```diff
@@ -130,6 +134,11 @@ public function run()
             }
         }
 
+        if ($this->uncaughtThrowable !== null) {
+            $this->logger->critical('rjobqueue.worker shutdown due to uncaught exception');
```
Comment (jmalloc) [inline src/Amqp/JobQueue/AmqpWorker.php]: typo `rjobqueue.worker`

File: src/Amqp/JobQueue/AmqpWorker.php [hunk 5]
```diff
@@ -195,19 +204,28 @@ private function recv(AMQPMessage $message)
...
+                try {
+                    $fn = $this->errorHandler;
+                    $fn($e);
+                } catch (Throwable $e) {
+                    $this->isStopping = true;
+                    $this->uncaughtThrowable = $e;
+                }
+            }
+
+            if ($e instanceof Error) {
```
Comment (jmalloc) [inline src/Amqp/JobQueue/AmqpWorker.php]: What does this do? It looks like it will hide the real exception from the log context?

Comment (darianbr) [inline src/Amqp/JobQueue/AmqpWorker.php]: It just converts the Error to an Exception
